[tasks.clean]
help = "Remove all cache and generated files"
script = "poethepoet.scripts:rm('./**/__pycache__', './**/*.pyc', './**/*.pyo')"

[tasks.lint]
help = "Run ruff linter with diff (pass directory/file as arg)"
cmd = "ruff check ${path} --diff"
args = [{ name = "path", default = ".", positional = true, multiple = true }]

[tasks.format]
help = "Check formatting with diff (pass directory/file as arg)"
cmd = "ruff format ${path} --check --diff"
args = [{ name = "path", default = ".", positional = true, multiple = true }]

[tasks.compose_up]
help = "Start Neo4j and run migrations"
cwd = "docker"
cmd = "docker compose --env-file=../.env up -d --build"

[tasks.compose_down]
help = "Stop and remove volumes"
cwd = "docker"
cmd = "docker compose --env-file=../.env down -v"

[tasks.seed]
help = "Seed the Neo4j Database"
cmd = "python sixdegrees/ingest/seeder.py"
executor = { type = "uv" }
