services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    ports:
      - "7474:7474" # browser ui
      - "7687:7687" # bolt proto
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7474"]
      interval: 5s
      timeout: 3s
      retries: 3

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    command: >
      --address bolt://neo4j:7687 --username neo4j --password ${NEO4J_PASSWORD}
      --location file:///migrations migrate
    depends_on:
      neo4j:
        condition: service_healthy
    restart: on-failure

  seeder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python -m sixdegrees.ingest.seeder
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    volumes:
      - ../data/processed:/app/data/processed:ro
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: on-failure

  flask:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      NEO4J_URI: bolt://neo4j:7687 # server-side: internal
      NEO4J_BOLT_BROWSER_URI: bolt://127.0.0.1:7687 # client-side: browser
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    depends_on:
      seeder:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  neo4j_data:
